[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aiverse-api"
version = "1.0.0"
description = "AIVerse Backend API"
requires-python = ">=3.11"
